cosmology:
  Omega_m: 
    min: 0.1
    max: 0.7
  Omega_b: 
    min: 0.04
    max: 0.06
  h: 
    min: 0.6
    max: 0.8
  sigma_8: 
    min: 0.6
    max: 1.1
  ns: 
    min: 0.9
    max: 1.0
  tau: 
    min: 0.04
    max: 0.08

simulation:
  num_sims: 10                  
  l_max: 3000                  
  CMB_unit: "muK"              
  accuracy_boost: 1.0       
  non_linear: "both"            
  lensing: True                 